/*! \file blinky.c
 *
 *  \brief LED flashing task
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "pwm.h"
#include "task.h"

#include <stdint.h>

#define BLINKY_TICK 20

static uint8_t blinky_task(uint8_t ms_later)
{
    static uint8_t wait;

    switch(ms_later)
    {
    case TASK_STARTUP:
        wait = 0;
        break;
    case TASK_SHUTDOWN:
        break;
    default:
        wait += ms_later;
        if (wait < BLINKY_TICK)
            break;
        wait -= BLINKY_TICK;
        /* Fade up, rollover at 255/5 = 51 ticks */
        pwm_set(0, pwm_get(0)+5);
        break;
    }

    return BLINKY_TICK-wait;
}

TASK_DECLARE(blinky_task);
