/*! \file test_pwm.c
 *
 *  \brief Software Pulse Width Modulation unit test
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "unity.h"  /* Framework */

#include "pwm.h"    /* Module under test */

#define TASK_STUB "../stubs/task.h"
#include TASK_STUB
#include "../stubs/avr/io.h"

/** task.c mock */
TASK_IMPORT(pwm_task);

/** avr/io.h mock */
unsigned char PORTA, DDRA, PORTB, DDRB, PORTC, DDRC;


void setUp(void)
{
}

void tearDown(void)
{
}

void test_init(void)
{
    DDRA=DDRB=DDRC=0;

    TASK_CYCLE(pwm_task)(TASK_STARTUP);

    TEST_ASSERT_EQUAL(1<<1, DDRA);
    TEST_ASSERT_EQUAL(1<<2, DDRB);
    TEST_ASSERT_EQUAL(1<<3, DDRC);
}
