/*! \file blinky.c
 *
 *  \brief LED flashing task
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "task.h"

#include <stdint.h>
#include <avr/io.h>

static uint8_t blinky_task(uint8_t ms_later)
{
    switch(ms_later)
    {
    case TASK_STARTUP:
        DDRB |= 2;  /* PB1 is output */
        break;
    case TASK_SHUTDOWN:
        DDRB &= ~2; /* PB1 is hi-Z */
        break;
    default:
        PORTB ^= 2; /* PB1 invert level */
        break;
    }

    /* Minimum 2Hz blink but actually follows most wakeful task */
    return 250;
}

TASK_DECLARE(blinky_task);
