/*! \file sleep.h
 *
 *  \brief AVR sleep stub
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

extern void mock_sleep_enable(void);
#define sleep_enable mock_sleep_enable

extern void mock_sleep_cpu(void);
#define sleep_cpu mock_sleep_cpu

enum sleep_mode
{
    SLEEP_MODE_IDLE = 0x123,
    SLEEP_MODE_PWR_DOWN = 0x234,
};

extern void mock_set_sleep_mode(enum sleep_mode);
#define set_sleep_mode mock_set_sleep_mode


extern unsigned char TCCR0A;
extern unsigned char TCCR0B;
extern unsigned char TCNT0;
extern unsigned char OCR0A;
extern unsigned char TIMSK;

extern unsigned F_CPU;
